config/routes.rb
ASingleLink::Application.routes.draw do
  resources :submitted_links

  
  resource :link, :only => :show
  root :to => 'links#show'

  resources :users

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/sign_out', :to => 'sessions#destroy'
  match '/submit_link', :to => 'submitted_links#new'
  

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
end

app/models/submitted_link.rb
class SubmittedLink < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :current_user
  
  protected 
  
  def current_user
    user_id = session[:current_user_id]
    
    @user = User.find_by_id user_id
    return @user
  end
  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def create
  end
  
  def show
    @link = Link.last
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
      
      auth = request.env["rack.auth"]
      
      facebook_id = auth['uid']
      first_name = auth['user_info']['first_name']
      last_name = auth['user_info']['last_name'] 
      email = auth['extra']['user_hash']['email'] 
    
      user = User.find_by_facebook_id(facebook_id)
      
      if user.nil?
        user = User.create :facebook_id => facebook_id, 
                            :first_name => first_name,
                            :last_name => last_name, 
                            :email => email
      end
      
      session[:current_user_id] = user.id
      
      redirect_to '/'
  end
  
  def destroy
    session[:current_user_id] = nil
    redirect_to '/'
  end
end

app/controllers/submitted_links_controller.rb
class SubmittedLinksController < ApplicationController
  # GET /submitted_links
  # GET /submitted_links.xml
  def index
    @submitted_links = SubmittedLink.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @submitted_links }
    end
  end

  # GET /submitted_links/1
  # GET /submitted_links/1.xml
  def show
    @submitted_link = SubmittedLink.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @submitted_link }
    end
  end

  # GET /submitted_links/new
  # GET /submitted_links/new.xml
  def new
    @submitted_link = SubmittedLink.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @submitted_link }
    end
  end

  # GET /submitted_links/1/edit
  def edit
    @submitted_link = SubmittedLink.find(params[:id])
  end

  # POST /submitted_links
  # POST /submitted_links.xml
  def create
    @submitted_link = SubmittedLink.new(params[:submitted_link])
    @submitted_link.user_id = current_user.id
    
    respond_to do |format|
      if @submitted_link.save
        format.html { redirect_to(@submitted_link, :notice => 'Submitted link was successfully created.') }
        format.xml  { render :xml => @submitted_link, :status => :created, :location => @submitted_link }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @submitted_link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /submitted_links/1
  # PUT /submitted_links/1.xml
  def update
    @submitted_link = SubmittedLink.find(params[:id])

    respond_to do |format|
      if @submitted_link.update_attributes(params[:submitted_link])
        format.html { redirect_to(@submitted_link, :notice => 'Submitted link was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @submitted_link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /submitted_links/1
  # DELETE /submitted_links/1.xml
  def destroy
    @submitted_link = SubmittedLink.find(params[:id])
    @submitted_link.destroy

    respond_to do |format|
      format.html { redirect_to(submitted_links_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/submitted_links_helper.rb
module SubmittedLinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A Single Link</title>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag "print/print.css", :media => "print" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div class="container">
		<div class="span-24">
			<div class="span-20">
				<h1 class="loud">
					A Single Link
				</h1>
				 <h4 class="alt">Reasonable discussions.</h4>
				<% if ! @user.nil? %>
					<a href="/submit_link">submit a link</a>
				<% end %>
			</div>
			<div class="span-4 last">
				<div class="box">
					<% if @user.nil? %>
						<a href="/auth/facebook">Login</a>
					<% else %>
						Hello <%= @user.first_name %> <%= @user.last_name %><br/>
						<a href="/sign_out">Logout</a>
					<% end %>
				</div>
			</div>
		</div>
		<hr />
<%= yield %>
		<div class="span-4 last">
			<div class="box">
				right sidebar
			</div>
		</div>
	</div>
</body>
</html>

app/views/links/show.html.erb
	
	<div class="span-20">
		<div class="box">
			<span class="quiet">
				<a href='<%= @link.url %>'><%= @link.description %></a>
			</span>
		</div>
	</div>

app/views/submitted_links/_form.html.erb
<%= form_for(@submitted_link) do |f| %>
  <% if @submitted_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submitted_link.errors.count, "error") %> prohibited this submitted_link from being saved:</h2>

      <ul>
      <% @submitted_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submitted_links/edit.html.erb
<h1>Editing submitted_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @submitted_link %> |
<%= link_to 'Back', submitted_links_path %>

app/views/submitted_links/index.html.erb
<h1>Listing submitted_links</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Title</th>
    <th>Description</th>
    <th>Thumbnail url</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @submitted_links.each do |submitted_link| %>
  <tr>
    <td><%= submitted_link.url %></td>
    <td><%= submitted_link.title %></td>
    <td><%= submitted_link.description %></td>
    <td><%= submitted_link.thumbnail_url %></td>
    <td><%= submitted_link.user %></td>
    <td><%= link_to 'Show', submitted_link %></td>
    <td><%= link_to 'Edit', edit_submitted_link_path(submitted_link) %></td>
    <td><%= link_to 'Destroy', submitted_link, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Submitted link', new_submitted_link_path %>

app/views/submitted_links/new.html.erb
<h1>New submitted_link</h1>

<%= render 'form' %>

<%= link_to 'Back', submitted_links_path %>

app/views/submitted_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @submitted_link.url %>
</p>

<p>
  <b>Title:</b>
  <%= @submitted_link.title %>
</p>

<p>
  <b>Description:</b>
  <%= @submitted_link.description %>
</p>

<p>
  <b>Thumbnail url:</b>
  <%= @submitted_link.thumbnail_url %>
</p>

<p>
  <b>User:</b>
  <%= @submitted_link.user %>
</p>


<%= link_to 'Edit', edit_submitted_link_path(@submitted_link) %> |
<%= link_to 'Back', submitted_links_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>